{% set name = "lightning" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: 7f454711895c1c6e455766f01fa39522e25e5ab54c15c5e5fbad342fa92bc93c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - fsspec <2026.0,>=2022.5.0
    - lightning-utilities <2.0,>=0.10.0
    - numpy <3.0,>=1.17.2
    - packaging <25.0,>=20.0
    - python >=3.8
    - pytorch <4.0,>=2.0.0
    - pytorch-lightning
    - pyyaml <8.0,>=5.4
    - torchmetrics <3.0,>=0.7.0
    - tqdm <6.0,>=4.57.0
    - typing-extensions <6.0,>=4.4.0

test:
  imports:
    - lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/lightning/app/cli/component-template/LICENSE
    - src/lightning/app/cli/app-template/LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
