{% set name = "lightning" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: 4cc3fb3edf04fcd63c0ecf75087d2fa06163759fc8c1fc500b16404ac1854f77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - fsspec <2025.0,>=2022.5.0
    - lightning-utilities <2.0,>=0.8.0
    - numpy <3.0,>=1.17.2
    - packaging <25.0,>=20.0
    - python >=3.8
    - pytorch <4.0,>=1.13.0
    - pytorch-lightning
    - pyyaml <8.0,>=5.4
    - torchmetrics <3.0,>=0.7.0
    - tqdm <6.0,>=4.57.0
    - typing-extensions <6.0,>=4.4.0

test:
  imports:
    - lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/lightning/app/cli/component-template/LICENSE
    - src/lightning/app/cli/app-template/LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
