{% set name = "lightning" %}
{% set version = "2.0.9.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: 93687b65bff28cedfc13c758bdfed982849c34f9bb506937c63275a9647586a0

build:
  entry_points:
    - lightning = lightning.app.cli.lightning_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - arrow <3.0,>=1.2.0
    - backoff <4.0,>=2.2.1
    - beautifulsoup4 <6.0,>=4.8.0
    - click <10.0
    - croniter <1.5.0,>=1.3.0
    - dateutils <2.0
    - deepdiff <8.0,>=5.7.0
    - fastapi <2.0,>=0.92.0
    - fsspec <2025.0,>=2022.5.0
    - inquirer <5.0,>=2.10.0
    - jinja2 <5.0
    - lightning-cloud >=0.5.38
    - lightning-utilities <2.0,>=0.7.0
    - numpy <3.0,>=1.17.2
    - packaging
    - psutil <7.0
    - pydantic <2.2.0,>=1.7.4
    - python >=3.8
    - python-multipart <2.0,>=0.0.5
    - pytorch <4.0,>=1.11.0
    - pytorch-lightning
    - pyyaml <8.0
    - requests <4.0
    - rich <15.0,>=12.3.0
    - starlette
    - starsessions <2.0,>=1.2.1
    - torchmetrics <3.0,>=0.7.0
    - tqdm <6.0,>=4.57.0
    - traitlets <7.0,>=5.3.0
    - typing-extensions <6.0,>=4.0.0
    - urllib3 <4.0
    - uvicorn <2.0
    - websocket-client <3.0
    - websockets <13.0

test:
  imports:
    - lightning
  commands:
    - pip check
    - LIGHTING_TESTING=1 lightning --help
  requires:
    - pip
    - python >=3.7, <3.11 # TODO: this upper bound is because of PyTorch issue with dataclass

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/lightning/app/cli/component-template/LICENSE
    - src/lightning/app/cli/app-template/LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
