{% set name = "lightning" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: 9156604cc56e4b2b603f34fa7f0fe5107375c8e6d85e74544b319a15faa9ed0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - packaging
    - pip
    - python >=3.9
    - setuptools
    - wheel
  run:
    - fsspec <2026.0,>=2022.5.0
    - lightning-utilities <2.0,>=0.10.0
    - packaging <25.0,>=20.0
    - python >=3.9
    - pytorch <4.0,>=2.1.0
    - pytorch-lightning
    - pyyaml <8.0,>=5.4
    - torchmetrics <3.0,>=0.7.0
    - tqdm <6.0,>=4.57.0
    - typing-extensions <6.0,>=4.4.0

test:
  imports:
    - lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
