{% set name = "lightning" %}
{% set version = "2.5.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: f720fe4f6d03a7f15f9aef3112c5a0d1eafd8d27b903f4a1354b609685b2ec70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - packaging
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - typing_extensions <6.0,>=4.4.0
    - fsspec <2026.0,>=2022.5.0
    - lightning-utilities <2.0,>=0.10.0
    - packaging <25.0,>=20.0
    - python >={{ python_min }}
    - pytorch <4.0,>=2.1.0
    - pytorch-lightning
    - pyyaml <8.0,>=5.4
    - torchmetrics <3.0,>=0.7.0
    - tqdm <6.0,>=4.57.0
    - typing-extensions <6.0,>=4.4.0

test:
  imports:
    - lightning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
